# -*- restclient -*-
#
# Gets  all Github APIs, formats JSON, shows response status and headers underneath.
# Also sends a User-Agent header, because the Github API requires this.
#

# Get all the recipes
GET http://localhost:8080/recipe

# Create new recipe
POST http://localhost:8080/recipe
Content-Type: application/json

{
        "title": "Great recipe",
        "ingredients": ["Salt", "Tomato", "Sugar"],
        "duration": "120 min",
        "steps": ["Mix everything"]
}

# Get a specific recipe
GET http://localhost:8080/recipe/36050b3f-35cb-4360-b905-0794a80e73e2

# Modify a specific recipe
PUT http://localhost:8080/recipe/36050b3f-35cb-4360-b905-0794a80e73e2
Content-Type: application/json

{
        "title": "Bad recipe",
        "duration": "34 min"
}

# Delete a recipe
DELETE http://localhost:8080/recipe/36050b3f-35cb-4360-b905-0794a80e73e2
